all:
  hosts:
    winhost_local_1:
      ansible_host: 192.168.0.11
      ansible_user: Aklil
      ansible_connection: winrm
      ansible_port: 5986
      ansible_winrm_transport: certificate
      ansible_winrm_cert_pem: /C:/Users/aklil/Documents/azkiflay_ansible_windows.cer
      ansible_winrm_cert_key_pem: azkiflay_ansible_windows.key
      ansible_winrm_server_cert_validation: ignore
